# Generated by Django 3.1.2 on 2020-11-08 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201108_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation'),
        ),
    ]
